#ifndef GLOBAL_H
#define GLOBAL_H

#define LOCAL_WORK_SIZE_X 16
#define LOCAL_WORK_SIZE_Y 16

#define WIDTH  (512+2*LOCAL_WORK_SIZE_X)
#define HEIGHT (512+2*LOCAL_WORK_SIZE_Y)

#define SCREEN_WIDTH  1024
#define SCREEN_HEIGHT 1024

#define BUFFER_SIZE 16384

#define DEPTH  4

#define NUM_WORK_GROUPS_X (WIDTH/LOCAL_WORK_SIZE_X)
#define NUM_WORK_GROUPS_Y (HEIGHT/LOCAL_WORK_SIZE_Y)

#define ETA 0.5f
#define DELTA_X (1.0f/(WIDTH-2*LOCAL_WORK_SIZE_X))
#define DELTA_Y (1.0f/(HEIGHT-2*LOCAL_WORK_SIZE_Y))

#endif // GLOBAL_H
